#Write code to check a String is palindrome or not

from practiceProg import practiceProg


practiceprog = practiceProg ()

#practiceprog.isPallindrom("dad")
#practiceprog.removeChar("mothervvszfzfafe", "e")
#practiceprog.nonRepChar("swisss")
#practiceprog.countOcc("swiss")
#practiceprog.anargram("iceman", "cinemas")
#practiceprog.findNum([1,2,3,4,5,6,7,8,9])
#practiceprog.countDupli([1,2,2,3,4,5,6,6,7,8,9,10])
#practiceprog.matchArray([1,2,3,4,5],[2,3,1,0,5])
#practiceprog.secondHighest([1,2,3,4,5])
#practiceprog.findPairEqualToSum([1,2,3,4,5], 8)
#practiceprog.removeDupli([1,2,3,3,3,4,5,6,7])
#practiceprog.findNums([1,2,3,3,3,4,5,6,7])
#practiceprog.firstDupliLowestIndex([8, 4, 6, 2, 6, 4, 7, 9, 5, 8])
#practiceprog.revInt(123)
#practiceprog.checkBin(199)
#practiceprog.camelCase('ab_ba')
#practiceprog.revSent("The sky is blue")
#practiceprog.rotation([1,2,3,4], 1)
#practiceprog.anargrams("abcd", "abc")
#practiceprog.ransomNote(6,5, "two times three is not four", "two times two is four")
#practiceprog.findIntk([5,1,2,3,4,5,1],1)
#practiceprog.oddNumbers(3,9)
#practiceprog.powerIndex(3)
#practiceprog.upperCase("ab")
#practiceprog.lonelyinteger([1,1,2])
#practiceprog.diagonal([[1,2,3], [4,5,6], [7,8,9]])
#practiceprog.hackerrank("hackerrankssss")
#practiceprog.camelCase1("saveChangesInTheEditor")
#practiceprog.balanceparenthesis("{[(])}")
#practiceprog.realBalanced("[[([[]({[]}())])]](){}()()[]()[()][{}()](){[]}")
#practiceprog.mapCavity(4, [1112,1912,1892,1234])
#practiceprog.number_needed("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
#practiceprog.ransom_note("give me one grand today tonight", "give one grand today")
#practiceprog.super_reduced_string("aa")
#print(practiceprog.test("Atvt hrqgse, Cnikg."))
#practiceprog.virus([11, 2, 4], [5,7, 8], [1,2,3])
#practiceprog.createStr("bghrbedbathandbeyondsderff")
#practiceprog.deleteWords("abc def ghi pqr", "abc ghi")
#practiceprog.removeOcurance("A Statement is a Statement Statement", "A Statement is Statement")
#practiceprog.shortestSubstring("aabbbcccbad")
#practiceprog.consecutiveCount("aabbbaacd")
#practiceprog.consecutiveCount1("aaaabqqbbaacd")
#practiceprog.twoSum([3,2,4], 7)
#practiceprog.reverseAlgo("!@#$")
